services:
  postgres:
    image: postgres:17.6-alpine
    container_name: furusake-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: furusake
      POSTGRES_USER: furusake
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U furusake -d furusake"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local