import type { Metadata } from "next";
import "./globals.css";
import type { FC, ReactNode } from "react";

type RootLayoutProps = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="ja">
    <body>{children}</body>
  </html>
);

export default RootLayout;
