set dotenv-load

migrate-up:
    goose -dir migrations postgres "${DATABASE_URL}" up

migrate-down:
    goose -dir migrations postgres "${DATABASE_URL}" down

migrate-status:
    goose -dir migrations postgres "${DATABASE_URL}" status

migrate-create name type="sql":
    goose -dir migrations create {{name}} {{type}}

migrate-reset:
    goose -dir migrations postgres "${DATABASE_URL}" reset

migrate-version:
    goose -dir migrations postgres "${DATABASE_URL}" version
