set dotenv-load

database_url := "postgres://" + env_var("DB_USER") + ":" + env_var("DB_PASSWORD") + "@" + env_var("DB_HOST") + ":" + env_var("DB_PORT") + "/" + env_var("DB_NAME") + "?sslmode=disable"

migrate-up:
    go tool goose -dir migrations postgres "{{database_url}}" up

migrate-down:
    go tool goose -dir migrations postgres "{{database_url}}" down

migrate-status:
    go tool goose -dir migrations postgres "{{database_url}}" status

migrate-create name type="sql":
    go tool goose -dir migrations create {{name}} {{type}}

migrate-reset:
    go tool goose -dir migrations postgres "{{database_url}}" reset

migrate-version:
    go tool goose -dir migrations postgres "{{database_url}}" version
