name: Go Check

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - ".github/workflows/golang-check.yaml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - ".github/workflows/golang-check.yaml"

defaults:
  run:
    working-directory: ./api

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: go.mod
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
