name: Terraform Plan

on:
  workflow_run:
    workflows: ["Terraform Check"]
    types:
      - completed

defaults:
  run:
    working-directory: ./infra

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get Target Branch
        id: get-target-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --head ${{ github.event.workflow_run.head_branch }} --repo ${{ github.repository }} --state all --json number --jq '.[0].number')
          if [ -z "$pr_number" ]; then
            echo "No PR found for branch ${{ github.event.workflow_run.head_branch }}"
            exit 1
          fi
          base_branch=$(gh pr view $pr_number --repo ${{ github.repository }} --json baseRefName --jq '.baseRefName')
          echo "base_branch=$base_branch" >> $GITHUB_OUTPUT
      - name: Check Environments
        run: |
          if [[ "${{ steps.get-target-branch.outputs.base_branch }}" == "develop" ]]; then
            echo "environment=develop" >> "$GITHUB_OUTPUT"
          elif [[ "${{ steps.get-target-branch.outputs.base_branch }}" == "main" ]]; then
            echo "environment=main" >> "$GITHUB_OUTPUT"
          else
            echo "Unknown Environment"
            exit 1

  plan:
    runs-on: ubuntu-latest
    needs: check-env
    defaults:
      run:
        working-directory: ./infra/environments/${{ needs.check-env.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup tfcmt
        uses: shmokmt/actions-setup-tfcmt@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -- terraform plan
   