name: Terraform Apply

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "infra/**"
      - ".github/workflows/**"

concurrency:
  group: terraform-apply-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./infra/environments/${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        env:
          TF_VAR_google_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          TF_VAR_vercel_api_token: ${{ secrets.VERCEL_API_TOKEN }}
          TF_VAR_vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          TF_VAR_expo_eas_token: ${{ secrets.EXPO_EAS_TOKEN }}
          TF_VAR_expo_account_name: ${{ secrets.EXPO_ACCOUNT_NAME }}
        run: terraform apply -auto-approve
