name: Terraform Plan

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "infra/**"
      - ".github/workflows/terraform-check.yaml"

defaults:
  run:
    working-directory: ./infra

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - main
          - develop
    defaults:
      run:
        working-directory: ./infra/environments/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
      - name: Cache plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint --recursive --config $(pwd)/.tflint.hcl --format compact

  plan:
    runs-on: ubuntu-latest
    needs:
      - terraform-fmt
      - terraform-validate
      - tflint
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./infra/environments/${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check Environments
        run: |
          if [[ ! "main development" =~ "${{ github.event.pull_request.base.ref }}" ]]; then
            echo "[ERROR] Unknown Environment (${{ github.event.pull_request.base.ref }})"
            exit 1
          fi
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup tfcmt
        uses: shmokmt/actions-setup-tfcmt@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -- terraform plan
