name: Terraform Check

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-check.yaml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-check.yaml'

defaults:
  run:
    working-directory: ./infra

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - main
          - develop
    defaults:
      run:
        working-directory: ./infra/environments/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
      - name: Cache plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint --recursive --config $(pwd)/.tflint.hcl --format compact